// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khywmagalxndtpssaaro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoeXdtYWdhbHhuZHRwc3NhYXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTAzNzEsImV4cCI6MjA3MzgyNjM3MX0.5v_5iNYiGghnd5uy6_B6d1l-Spl5depspsIsQnSyr9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});